# Generated by Django 2.0.2 on 2018-02-17 12:10

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryBayar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bayar_sisa', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='kekurangan pembayaran')),
                ('bayar_now', models.DecimalField(decimal_places=2, max_digits=14)),
            ],
        ),
        migrations.CreateModel(
            name='Jabat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jabatan', models.CharField(max_length=7)),
                ('nama', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Kontrak',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_kontrak', models.CharField(max_length=20)),
                ('supplier', models.CharField(max_length=200)),
                ('deskripsi', models.CharField(max_length=500)),
                ('tgl_terbit', models.DateField(default=datetime.date.today)),
                ('tgl_due', models.DateField(default=datetime.date.today)),
                ('nilai', models.DecimalField(decimal_places=2, max_digits=14)),
                ('nhari_har', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Ppm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ketua', models.CharField(max_length=7)),
                ('sekretaris', models.CharField(max_length=7)),
                ('anggota', models.CharField(max_length=7)),
                ('kontrak', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='printapp.Kontrak')),
            ],
        ),
        migrations.CreateModel(
            name='Receiving',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_bapp', models.CharField(help_text='Nomer Berita Acara Pemeriksaan Pekerjaan', max_length=27)),
                ('tgl_bapp', models.DateField(default=datetime.date.today)),
                ('no_bast', models.CharField(help_text='Nomer Berita Acara Serah Terima Pekerjaan', max_length=27)),
                ('tgl_bast', models.DateField(default=models.DateField(default=datetime.date.today))),
                ('tgl_periksa', models.DateField(default=datetime.date.today, help_text='Tanggal Pelaksanaan Pemeriksaan di Lapangan')),
                ('bayar_now', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='pembayaran sekarang')),
                ('nhari_telat', models.IntegerField(default=0, verbose_name='jumlah hari keterlambatan')),
                ('bayar_prev', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='printapp.HistoryBayar', verbose_name='pembayaran sebelumnya')),
            ],
        ),
        migrations.CreateModel(
            name='Termin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tgl_termin', models.DateField(default=datetime.date.today)),
                ('nilai_termin', models.DecimalField(decimal_places=2, max_digits=14)),
                ('nth_termin', models.IntegerField(default=1)),
                ('kontrak', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='printapp.Kontrak')),
            ],
        ),
        migrations.AddField(
            model_name='receiving',
            name='termin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='printapp.Termin'),
        ),
        migrations.AddField(
            model_name='historybayar',
            name='no_bast',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='printapp.Receiving'),
        ),
    ]
