# Generated by Django 2.0.2 on 2018-02-17 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('printapp', '0002_auto_20180217_1917'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kontrak',
            options={'ordering': ['tgl_terbit']},
        ),
    ]
