# Generated by Django 2.0.2 on 2018-02-18 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printapp', '0003_auto_20180217_2154'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jabat',
            options={'ordering': ('jabatan',)},
        ),
        migrations.AlterField(
            model_name='ppm',
            name='ketua',
            field=models.CharField(blank=True, choices=[('MENG', 'Mhghghgh'), ('MOPH', 'kjkjkjkj'), ('MKAD', 'uoioioio')], default='MOPH', max_length=4),
        ),
    ]
