# Generated by Django 2.0.2 on 2018-02-18 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printapp', '0006_auto_20180218_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ppm',
            name='ketua',
            field=models.CharField(blank=True, choices=[('MENG', 'Manager Enjenering'), ('MOPH', 'Manager Operasi Pemeliharaan'), ('MADM', 'Manajer Administrasi dan Keuangan')], default='MOPH', max_length=4, unique=True),
        ),
    ]
