# Generated by Django 2.0.2 on 2018-02-18 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('printapp', '0007_auto_20180218_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ppm',
            name='ketua',
            field=models.CharField(blank=True, choices=[('MENG', 'Manager Enjenering'), ('MOPH', 'Manager Operasi Pemeliharaan'), ('MADM', 'Manajer Administrasi dan Keuangan')], default='MOPH', max_length=4),
        ),
        migrations.AlterField(
            model_name='ppm',
            name='kontrak',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='printapp.Kontrak', unique=True),
        ),
    ]
