# Generated by Django 2.0.2 on 2018-02-22 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printapp', '0008_auto_20180218_2159'),
    ]

    operations = [
        migrations.AddField(
            model_name='kontrak',
            name='status',
            field=models.CharField(blank=True, choices=[('o', 'open'), ('p', 'partial'), ('c', 'closed')], default='o', max_length=7),
        ),
    ]
